version: "3.9"

services:
  frontend:
    build: ./client
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - rdp-app
    volumes:
      - ./client/:/usr/src/app/client/
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54322:5432"
    networks:
      - rdp-app
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - rdp-app
    depends_on:
      - db
networks:
  rdp-app:
    driver: bridge
volumes:
  postgres_data:
    driver: local