FROM python:3

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/back

COPY requirements.txt /usr/src/back

RUN pip install -r requirements.txt

COPY . /usr/src/back

RUN python manage.py makemigrations
RUN python manage.py migrate